#!/usr/bin/env ruby

require 'minitest/autorun'
require_relative '../remotes/hooks/alias_ip/vnfilter'

# Run the production reconciliation against a simulated ebtables backend. The
# backend can commit a command and then fail, matching the ambiguous nft race.
class AliasHookBackend
    attr_reader :commands, :pauses
    attr_accessor :failures, :inventory_failure, :incomplete_inventory, :inventory

    def initialize(add: true)
        @add = add
        @rules = Hash.new(0)
        @commands = []
        @pauses = []
        @failures = []
        @inventory_failure = nil
        @inventory_reads = 0
    end

    def log(*); end
    def log_error(*); end
    def sleep(seconds); @pauses << seconds; end

    def count(direction)
        @rules[direction]
    end

    def seed(direction, count)
        @rules[direction] = count
    end

    def capture(argv)
        if argv.last == 'ebtables-save'
            @inventory_reads += 1
            return ['', 'Permission denied', false] if @inventory_reads == @inventory_failure
            return ["*nat\n", '', true] if @incomplete_inventory
            return [@inventory, '', true] if @inventory

            lines = ["# Generated by ebtables-save v1.8.10 (nf_tables)\n*nat\n"]
            %w[i o].each do |direction|
                chain = "one-42-0-#{direction}-arp4"
                rule = direction == 'i' ? '--arp-ip-src' : '--arp-ip-dst'
                lines << ":#{chain} DROP\n"
                @rules[direction].times do
                    lines << "-A #{chain} -p ARP #{rule} 192.0.2.1/32 -j RETURN\n"
                end
            end
            lines << "# Completed on Wed Oct  7 14:57:05 2026\n"
            return [lines.join, '', true]
        end

        @commands << argv
        direction = argv.find { |arg| arg.match?(/one-42-0-[io]-arp4/) }.split('-')[-2]
        failure = @failures.shift
        applied = failure.nil? || failure[:applied]
        @rules[direction] += argv.include?('-A') ? 1 : -1 if applied
        ['', failure ? failure[:stderr] : '', failure.nil?]
    end

    def reconcile
        toggle_ebtables_filter(
            nicdev: 'one-42-0', action: @add ? 'add' : 'del',
            a: { ip: '192.0.2.1' }
        )
    end
end

class AliasHookRetriesTest < Minitest::Test
    TRANSIENT = 'RULE_DELETE failed (No such file or directory)'.freeze

    def fixture(name)
        File.read(File.join(__dir__, 'fixtures', 'ebtables-save', name))
    end

    def inventory_backend(name, add: true)
        backend = AliasHookBackend.new(add: add)
        backend.inventory = fixture(name)
        backend
    end

    def test_captured_nft_whitelist_is_counted_and_add_is_idempotent
        backend = inventory_backend('hv68-nft.txt')
        assert_equal 1, backend.send(:arp_rule_count, 'one-42-0-i-arp4', '--arp-ip-src', '192.0.2.1')
        assert_equal 1, backend.send(:arp_rule_count, 'one-42-0-o-arp4', '--arp-ip-dst', '192.0.2.1')
        assert backend.reconcile
        assert_empty backend.commands
    end

    def test_captured_nft_inventory_distinguishes_absent_addresses
        backend = inventory_backend('hv68-nft.txt')
        assert_equal 0, backend.send(:arp_rule_count, 'one-42-0-i-arp4', '--arp-ip-src', '192.0.2.99')
    end

    def test_captured_nft_empty_whitelist_delete_is_idempotent
        backend = inventory_backend('hv70-nft.txt', add: false)
        assert_equal 0, backend.send(:arp_rule_count, 'one-42-0-i-arp4', '--arp-ip-src', '192.0.2.1')
        assert backend.reconcile
        assert_empty backend.commands
    end

    def test_truncated_nat_is_not_completed_by_earlier_filter_marker
        backend = inventory_backend('hv68-nft.txt')
        backend.inventory = backend.inventory.sub(/# Completed on [^\n]+\n\z/, '')
        refute backend.reconcile
        assert_empty backend.commands
    end

    def test_next_table_cannot_complete_truncated_nat
        backend = inventory_backend('hv68-nft.txt')
        backend.inventory = backend.inventory.sub(/# Completed on [^\n]+\n\z/, '') +
                            "*broute\n:BROUTING ACCEPT\n# Completed on Wed Oct  7 14:57:05 2026\n"
        refute backend.reconcile
        assert_empty backend.commands
    end

    def test_completed_nat_does_not_count_rules_from_next_table
        backend = inventory_backend('hv70-nft.txt')
        backend.inventory += "*broute\n:one-42-0-i-arp4 DROP\n" \
                             "-A one-42-0-i-arp4 -p ARP --arp-ip-src 192.0.2.1 -j RETURN\nCOMMIT\n"
        assert_equal 0, backend.send(:arp_rule_count, 'one-42-0-i-arp4', '--arp-ip-src', '192.0.2.1')
    end

    def test_duplicate_nat_table_is_rejected
        backend = inventory_backend('hv68-nft.txt')
        backend.inventory += "*nat\nCOMMIT\n"
        refute backend.reconcile
        assert_empty backend.commands
    end

    def test_commit_delimited_inventory_remains_supported
        backend = inventory_backend('hv68-nft.txt')
        backend.inventory = backend.inventory.gsub(/# Completed on [^\n]+/, 'COMMIT')
        assert backend.reconcile
        assert_empty backend.commands
    end

    def test_add_verifies_both_directions_and_replay_is_idempotent
        backend = AliasHookBackend.new
        assert backend.reconcile
        assert backend.reconcile
        assert_equal [1, 1], %w[i o].map { |d| backend.count(d) }
        assert_equal 2, backend.commands.length
    end

    def test_inbound_failure_retries_only_failed_rule
        backend = AliasHookBackend.new
        backend.failures = [{ stderr: TRANSIENT, applied: false }]
        assert backend.reconcile
        assert_equal [1, 1], %w[i o].map { |d| backend.count(d) }
        assert_equal 3, backend.commands.length
        assert_equal [0.2], backend.pauses
    end

    def test_outbound_failure_does_not_replay_inbound_success
        backend = AliasHookBackend.new
        backend.failures = [nil, { stderr: TRANSIENT, applied: false }]
        assert backend.reconcile
        assert_equal [1, 1], %w[i o].map { |d| backend.count(d) }
        assert_equal 3, backend.commands.length
    end

    def test_applied_add_with_error_does_not_duplicate_rule
        backend = AliasHookBackend.new
        backend.failures = [{ stderr: TRANSIENT, applied: true }]
        assert backend.reconcile
        assert_equal [1, 1], %w[i o].map { |d| backend.count(d) }
        assert_equal 2, backend.commands.length
        assert_empty backend.pauses
    end

    def test_applied_delete_with_error_and_repeat_delete_are_successful
        backend = AliasHookBackend.new(add: false)
        %w[i o].each { |d| backend.seed(d, 1) }
        backend.failures = [{ stderr: TRANSIENT, applied: true }]
        assert backend.reconcile
        assert backend.reconcile
        assert_equal [0, 0], %w[i o].map { |d| backend.count(d) }
        assert_equal 2, backend.commands.length
    end

    def test_delete_removes_existing_duplicate_rules
        backend = AliasHookBackend.new(add: false)
        backend.seed('i', 3)
        backend.seed('o', 2)
        assert backend.reconcile
        assert_equal [0, 0], %w[i o].map { |d| backend.count(d) }
        assert_equal 5, backend.commands.length
    end

    def test_permanent_mutation_failure_is_not_retried
        backend = AliasHookBackend.new
        backend.failures = [{ stderr: 'Operation not permitted', applied: false }]
        refute backend.reconcile
        assert_equal 2, backend.commands.length
        assert_empty backend.pauses
    end

    def test_retry_exhaustion_reports_failure_and_remains_bounded
        backend = AliasHookBackend.new
        backend.failures = Array.new(10) { { stderr: TRANSIENT, applied: false } }
        refute backend.reconcile
        assert_equal 10, backend.commands.length
        assert_equal 8, backend.pauses.length
    end

    def test_inventory_read_failure_is_not_treated_as_absent_rule
        backend = AliasHookBackend.new
        backend.inventory_failure = 1
        refute backend.reconcile
        assert_equal 1, backend.commands.length # Only the other direction runs.
    end

    def test_post_mutation_read_failure_prevents_success
        backend = AliasHookBackend.new
        backend.inventory_failure = 2
        refute backend.reconcile
        assert_equal 2, backend.commands.length
    end

    def test_incomplete_inventory_prevents_all_mutations
        backend = AliasHookBackend.new
        backend.incomplete_inventory = true
        refute backend.reconcile
        assert_empty backend.commands
    end

    def test_busy_backend_is_retried
        backend = AliasHookBackend.new
        backend.failures = [{ stderr: 'Device or resource busy', applied: false }]
        assert backend.reconcile
        assert_equal [1, 1], %w[i o].map { |d| backend.count(d) }
    end
end
